spring.application.name=ecommerce
app.rabbitmq.stock.queue=${APP_RABBITMQ_STOCK_QUEUE}
app.rabbitmq.email.queue=${APP_RABBITMQ_EMAIL_QUEUE}
app.rabbitmq.invoice.queue=${APP_RABBITMQ_INVOICE_QUEUE}
app.rabbitmq.order.exchange=${APP_RABBITMQ_ORDER_EXCHANGE}
app.rabbitmq.order.paid=${APP_RABBITMQ_ORDER_PAID_ROUTING_KEY}
app.rabbitmq.dead-letter.exchange=${APP_RABBITMQ_DEAD_LETTER_EXCHANGE}
app.rabbitmq.order.dead-letter.queue=${APP_RABBITMQ_ORDER_DEAD_LETTER_QUEUE}
app.rabbitmq.order.dead-letter.routing-key=${APP_RABBITMQ_ORDER_DEAD_LETTER_ROUTING_KEY}

#Jwt configuration
app.jwt.expiration=${APP_JWT_EXPIRATION}
app.jwt.key=${APP_JWT_KEY}