spring.application.name=ecommerce

#Rabbitmq configuration
app.rabbitmq.stock.queue=${APP_RABBITMQ_STOCK_QUEUE}
app.rabbitmq.email.queue=${APP_RABBITMQ_EMAIL_QUEUE}
app.rabbitmq.invoice.queue=${APP_RABBITMQ_INVOICE_QUEUE}
app.rabbitmq.order.exchange=${APP_RABBITMQ_ORDER_EXCHANGE}
app.rabbitmq.order.paid=${APP_RABBITMQ_ORDER_PAID_ROUTING_KEY}
app.rabbitmq.dead-letter.exchange=${APP_RABBITMQ_DEAD_LETTER_EXCHANGE}
app.rabbitmq.order.dead-letter.queue=${APP_RABBITMQ_ORDER_DEAD_LETTER_QUEUE}
app.rabbitmq.order.dead-letter.routing-key=${APP_RABBITMQ_ORDER_DEAD_LETTER_ROUTING_KEY}
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

#Jwt configuration
app.jwt.expiration=${APP_JWT_EXPIRATION}
app.jwt.key=${APP_JWT_KEY}

#Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#Aws configuration
app.aws.region=${APP_AWS_REGION}
app.aws.secret.key=${APP_AWS_SECRET_KEY}
app.aws.access.key=${APP_AWS_ACCESS_KEY}
app.aws.bucket.name=${APP_AWS_BUCKET_NAME}

#File size configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB