name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./ecommerce
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce:${{ github.sha }} 
  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH Login & Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            docker compose -f docker-compose-ec2.yml pull app
            docker compose -f docker-compose-ec2.yml up -d


